### ISSUE TITLE
Not compatible with some localized versions of dotnet sdk 6.x

### ISSUE THREAD

**Issue by PurplestViper** [sethreno/ReGitLint#29] opened 2022-08-29 08:17 UTC
#20 
Reproduced in dotnet sdk 6.0.400 version

**Comment by balkarov** [comment] 2022-08-30 14:40
I have the same problem

**Comment by bkoelman** [comment] 2022-08-30 16:48
Are you using a global install of the Resharper tools, or locally using `./.config/dotnet-tools.json`? In the former case, you need to pass `--use-global` to regitlint.

Does that solve the problem?

**Comment by balkarov** [comment] 2022-08-30 17:07
@bkoelman  I use locally in donet-tools.json. 
where I need pass —use-global?

**Comment by bkoelman** [comment] 2022-08-30 18:13
See https://github.com/sethreno/ReGitLint/blob/master/ReGitLint/Cleanup.cs#L99-L102 and https://github.com/sethreno/ReGitLint/blob/master/ReGitLint/Cleanup.cs#L454-L459. But it does not apply if using locally.

**Comment by bkoelman** [comment] 2022-08-30 18:21
I can't reproduce the problem.
- Which OS are you using?
- Is dotnet in your path?
- What's the output of `dotnet tool run dotnetsay` and `dotnet dotnetsay`? (see https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#invoke-a-local-tool)

**Comment by bkoelman** [comment] 2022-08-30 18:25
When using locally, did you run `dotnet tool restore` first?

**Comment by bkoelman** [comment] 2022-08-30 18:30
The following may help to diagnose the root cause: https://docs.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues

**Comment by balkarov** [comment] 2022-08-31 06:56
@bkoelman 
1. I user windows 10.
2. Yes
3. 
![image](https://user-images.githubusercontent.com/6030335/187613291-e27dddec-822f-4925-92b1-cedabd58128c.png)

4. Yes, I did `dotnet tool restore`.

**Comment by PurplestViper** [comment] 2022-08-31 07:45
> I can't reproduce the problem.
> 
> * Which OS are you using?
> * Is dotnet in your path?
> * What's the output of `dotnet tool run dotnetsay` and `dotnet dotnetsay`? (see https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#invoke-a-local-tool)

This is a known bug of the .net 6 sdk，look this: https://github.com/dotnet/sdk/issues/24059.
Now all we need to do is append the command [`--`](https://docs.microsoft.com/en-us/dotnet/standard/commandline/syntax#the----token): `dotnet tool run jb -- cleanupcode`.

**Comment by balkarov** [comment] 2022-08-31 07:55
@Ruthlessist where do I need to add this? In task-runner.json?
Could you send me a working task-runner.json file please?

**Comment by PurplestViper** [comment] 2022-08-31 08:49
> @Ruthlessist where do I need to add this? In task-runner.json? Could you send me a working task-runner.json file please?

https://github.com/sethreno/ReGitLint/blob/893af70db214d6ca26fa9a3a2f7527e2fc7a5361/ReGitLint/Cleanup.cs#L383
https://github.com/sethreno/ReGitLint/blob/893af70db214d6ca26fa9a3a2f7527e2fc7a5361/ReGitLint/Cleanup.cs#L455

* Add `--` after jb, like `tool run jb -- cleanupcode`
* Or remove `tool run` to use [short form](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#invoke-a-local-tool), like `jb cleanupcode`, it's available.

**Comment by balkarov** [comment] 2022-08-31 08:51
@Ruthlessist maybe you can create PullRequest to this repo with fix? 
Or maybe @bkoelman  @sethreno  can fix it?

**Comment by PurplestViper** [comment] 2022-08-31 08:56
@balkarov I don't know how to run tests for this project

**Comment by bkoelman** [comment] 2022-09-03 14:25
> This is a known bug of the .net 6 sdk，look this: [dotnet/sdk#24059](https://github.com/dotnet/sdk/issues/24059). Now all we need to do is append the command [`--`](https://docs.microsoft.com/en-us/dotnet/standard/commandline/syntax#the----token): `dotnet tool run jb -- cleanupcode`.

@Ruthlessist thanks for tracking down what's causing this. If I understand correctly, the problem is caused by a bug in the .NET 6.x SDK and only occurs on some localized versions. A fix for the .NET 7 SDK was merged in July, but it's unclear to me whether that's going to be backported to .NET 6.

As I understand it, the `--` token exists to disambiguate between options and arguments, which is not what we're trying to solve. So while adding `--` may appear to workaround the bug in the SDK (note the use of `--` isn't even [documented](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#invoke-a-local-tool) for `dotnet tool`), I don't think ReGitLint should be implementing bandages over broken SDK versions.

There are no tests for ReGitLint, so it's hard to tell what new issues such a change to ReGitLint will introduce. The amount of work is not in creating a PR, but in testing it across SDK versions (including .NET Core 3.1 and .NET 5), operating systems, local/global tools and the combinations with other ReGitLint command-line switches. Unfortunately, the time I can spend on ReGitLint is very limited, and I suspect the same applies to @sethreno. I have verified that ReGitLint works properly on Windows and Ubuntu using non-localized v6.0.400 of the SDK.

While anyone can always fork the repro as a temporary solution, I think our efforts should be focused on getting the SDK bug fixed by upvoting or commenting on [dotnet/sdk#24059](https://github.com/dotnet/sdk/issues/24059).

@balkarov Can you confirm you're running a localized version of the SDK?

**Comment by PurplestViper** [comment] 2022-09-04 11:22
@bkoelman we can do without `--` token, but maybe we can try to use the officially supported [short form](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#invoke-a-local-tool) version to call the local tool, it seems to be more general, supported as early as .net core 2.2, look https://github.com/dotnet/sdk/issues/9910, https://github.com/dotnet/cli/pull/10980, https://github.com/dotnet/sdk/issues/3115 and it's still working fine until now.

I know it's not our fault, but if left alone, it's going to cause trouble for some current users.

**Comment by sethreno** [comment] 2022-09-05 13:27
Thanks everyone for reporting and researching. @Ruthlessist I don't mind adding a --shortForm flag for a workaround. Just to make sure I understand...

If I run the command

    dotnet regitlint

regitlint will generate and run the following command

    dotnet tool run jb cleanupcode "./ReGitLint.sln"

The request is to add a --shortForm flag so that regitlint will generate and run this command instead:

    dotnet jb cleanupcode "./ReGitLint.sln"

Can you confirm that this will solve your problem?

**Comment by PurplestViper** [comment] 2022-09-05 16:25
@sethreno the short form command does solve the current problem:
![image](https://user-images.githubusercontent.com/30370418/188488993-a40d6bb1-9d85-4d21-839a-712642db59c7.png)

**Closed as completed** 2022-11-25 17:23 UTC
